/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkflowsRouteImport } from './routes/_app.workflows'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppSiteRouteImport } from './routes/_app.site'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResourcesRouteImport } from './routes/_app.resources'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppEngineerRouteImport } from './routes/_app.engineer'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConsultantRouteImport } from './routes/_app.consultant'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppArchitectRouteImport } from './routes/_app.architect'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppAiInsightsRouteImport } from './routes/_app.ai-insights'
import { Route as AppFinanceIndexRouteImport } from './routes/_app.finance.index'
import { Route as AppArchitectIndexRouteImport } from './routes/_app.architect.index'
import { Route as AppProjectsNewRouteImport } from './routes/_app.projects.new'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppHrWorkforceRouteImport } from './routes/_app.hr.workforce'
import { Route as AppHrTrainingRouteImport } from './routes/_app.hr.training'
import { Route as AppHrSettingsRouteImport } from './routes/_app.hr.settings'
import { Route as AppHrScheduleRouteImport } from './routes/_app.hr.schedule'
import { Route as AppHrReportsRouteImport } from './routes/_app.hr.reports'
import { Route as AppHrRecruitmentRouteImport } from './routes/_app.hr.recruitment'
import { Route as AppHrPerformanceRouteImport } from './routes/_app.hr.performance'
import { Route as AppHrPayrollRouteImport } from './routes/_app.hr.payroll'
import { Route as AppHrNotificationsRouteImport } from './routes/_app.hr.notifications'
import { Route as AppHrLeaveRouteImport } from './routes/_app.hr.leave'
import { Route as AppHrEmployeesRouteImport } from './routes/_app.hr.employees'
import { Route as AppHrDocumentsRouteImport } from './routes/_app.hr.documents'
import { Route as AppHrDeductionsRouteImport } from './routes/_app.hr.deductions'
import { Route as AppHrBenefitsRouteImport } from './routes/_app.hr.benefits'
import { Route as AppHrAttendanceRouteImport } from './routes/_app.hr.attendance'
import { Route as AppHrAiRouteImport } from './routes/_app.hr.ai'
import { Route as AppFinanceReportsRouteImport } from './routes/_app.finance.reports'
import { Route as AppFinancePayrollReviewRouteImport } from './routes/_app.finance.payroll-review'
import { Route as AppFinanceExpensesRouteImport } from './routes/_app.finance.expenses'
import { Route as AppFinanceBudgetsRouteImport } from './routes/_app.finance.budgets'
import { Route as AppFinanceApprovalsRouteImport } from './routes/_app.finance.approvals'
import { Route as AppFinanceAiRouteImport } from './routes/_app.finance.ai'
import { Route as AppArchitectRevisionsRouteImport } from './routes/_app.architect.revisions'
import { Route as AppArchitectReviewsRouteImport } from './routes/_app.architect.reviews'
import { Route as AppArchitectDocumentationRouteImport } from './routes/_app.architect.documentation'
import { Route as AppArchitectDesignsRouteImport } from './routes/_app.architect.designs'
import { Route as AppArchitectBlueprintsRouteImport } from './routes/_app.architect.blueprints'
import { Route as AppArchitectAiRouteImport } from './routes/_app.architect.ai'
import { Route as AppArchitectRevisionsIndexRouteImport } from './routes/_app.architect.revisions.index'
import { Route as AppArchitectReviewsIndexRouteImport } from './routes/_app.architect.reviews.index'
import { Route as AppArchitectDocumentationIndexRouteImport } from './routes/_app.architect.documentation.index'
import { Route as AppArchitectDesignsIndexRouteImport } from './routes/_app.architect.designs.index'
import { Route as AppArchitectBlueprintsIndexRouteImport } from './routes/_app.architect.blueprints.index'
import { Route as AppProjectsProjectIdWorkforceRouteImport } from './routes/_app.projects.$projectId.workforce'
import { Route as AppProjectsProjectIdTimelineRouteImport } from './routes/_app.projects.$projectId.timeline'
import { Route as AppProjectsProjectIdTasksRouteImport } from './routes/_app.projects.$projectId.tasks'
import { Route as AppProjectsProjectIdRisksRouteImport } from './routes/_app.projects.$projectId.risks'
import { Route as AppProjectsProjectIdQualityRouteImport } from './routes/_app.projects.$projectId.quality'
import { Route as AppProjectsProjectIdMilestonesRouteImport } from './routes/_app.projects.$projectId.milestones'
import { Route as AppProjectsProjectIdIssuesRouteImport } from './routes/_app.projects.$projectId.issues'
import { Route as AppProjectsProjectIdEquipmentRouteImport } from './routes/_app.projects.$projectId.equipment'
import { Route as AppProjectsProjectIdDocumentsRouteImport } from './routes/_app.projects.$projectId.documents'
import { Route as AppProjectsProjectIdDailyLogsRouteImport } from './routes/_app.projects.$projectId.daily-logs'
import { Route as AppProjectsProjectIdAnalyticsRouteImport } from './routes/_app.projects.$projectId.analytics'
import { Route as AppHrRecruitmentInterviewsRouteImport } from './routes/_app.hr.recruitment.interviews'
import { Route as AppHrPayrollHistoryRouteImport } from './routes/_app.hr.payroll.history'
import { Route as AppHrPayrollApprovalsRouteImport } from './routes/_app.hr.payroll.approvals'
import { Route as AppHrAttendanceVerificationRouteImport } from './routes/_app.hr.attendance.verification'
import { Route as AppHrAttendanceIssuesRouteImport } from './routes/_app.hr.attendance.issues'
import { Route as AppHrAttendanceGeofenceRouteImport } from './routes/_app.hr.attendance.geofence'
import { Route as AppFinanceBudgetsHistoryRouteImport } from './routes/_app.finance.budgets.history'
import { Route as AppFinanceBudgetsComparisonRouteImport } from './routes/_app.finance.budgets.comparison'
import { Route as AppFinanceBudgetsApprovalRouteImport } from './routes/_app.finance.budgets.approval'
import { Route as AppFinanceBudgetsAnalyticsRouteImport } from './routes/_app.finance.budgets.analytics'
import { Route as AppFinanceBudgetsAllocationRouteImport } from './routes/_app.finance.budgets.allocation'
import { Route as AppFinanceBudgetsAdjustmentsRouteImport } from './routes/_app.finance.budgets.adjustments'
import { Route as AppFinanceBudgetsBudgetIdRouteImport } from './routes/_app.finance.budgets.$budgetId'
import { Route as AppArchitectRevisionsRevisionIdRouteImport } from './routes/_app.architect.revisions.$revisionId'
import { Route as AppArchitectReviewsReviewIdRouteImport } from './routes/_app.architect.reviews.$reviewId'
import { Route as AppArchitectDocumentationDocIdRouteImport } from './routes/_app.architect.documentation.$docId'
import { Route as AppArchitectDesignsNewRouteImport } from './routes/_app.architect.designs.new'
import { Route as AppArchitectDesignsDesignIdRouteImport } from './routes/_app.architect.designs.$designId'
import { Route as AppArchitectBlueprintsBlueprintIdRouteImport } from './routes/_app.architect.blueprints.$blueprintId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteRoute = AppSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppEngineerRoute = AppEngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultantRoute = AppConsultantRouteImport.update({
  id: '/consultant',
  path: '/consultant',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppArchitectRoute = AppArchitectRouteImport.update({
  id: '/architect',
  path: '/architect',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppArchitectIndexRoute = AppArchitectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppArchitectRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppHrWorkforceRoute = AppHrWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrTrainingRoute = AppHrTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrSettingsRoute = AppHrSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrScheduleRoute = AppHrScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrReportsRoute = AppHrReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrRecruitmentRoute = AppHrRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrPerformanceRoute = AppHrPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrPayrollRoute = AppHrPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrNotificationsRoute = AppHrNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrLeaveRoute = AppHrLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrEmployeesRoute = AppHrEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrDocumentsRoute = AppHrDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrDeductionsRoute = AppHrDeductionsRouteImport.update({
  id: '/deductions',
  path: '/deductions',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrBenefitsRoute = AppHrBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrAttendanceRoute = AppHrAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrAiRoute = AppHrAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppHrRoute,
} as any)
const AppFinanceReportsRoute = AppFinanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinancePayrollReviewRoute = AppFinancePayrollReviewRouteImport.update({
  id: '/payroll-review',
  path: '/payroll-review',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceExpensesRoute = AppFinanceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceBudgetsRoute = AppFinanceBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceApprovalsRoute = AppFinanceApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceAiRoute = AppFinanceAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppArchitectRevisionsRoute = AppArchitectRevisionsRouteImport.update({
  id: '/revisions',
  path: '/revisions',
  getParentRoute: () => AppArchitectRoute,
} as any)
const AppArchitectReviewsRoute = AppArchitectReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppArchitectRoute,
} as any)
const AppArchitectDocumentationRoute =
  AppArchitectDocumentationRouteImport.update({
    id: '/documentation',
    path: '/documentation',
    getParentRoute: () => AppArchitectRoute,
  } as any)
const AppArchitectDesignsRoute = AppArchitectDesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => AppArchitectRoute,
} as any)
const AppArchitectBlueprintsRoute = AppArchitectBlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => AppArchitectRoute,
} as any)
const AppArchitectAiRoute = AppArchitectAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppArchitectRoute,
} as any)
const AppArchitectRevisionsIndexRoute =
  AppArchitectRevisionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppArchitectRevisionsRoute,
  } as any)
const AppArchitectReviewsIndexRoute =
  AppArchitectReviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppArchitectReviewsRoute,
  } as any)
const AppArchitectDocumentationIndexRoute =
  AppArchitectDocumentationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppArchitectDocumentationRoute,
  } as any)
const AppArchitectDesignsIndexRoute =
  AppArchitectDesignsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppArchitectDesignsRoute,
  } as any)
const AppArchitectBlueprintsIndexRoute =
  AppArchitectBlueprintsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppArchitectBlueprintsRoute,
  } as any)
const AppProjectsProjectIdWorkforceRoute =
  AppProjectsProjectIdWorkforceRouteImport.update({
    id: '/workforce',
    path: '/workforce',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdTimelineRoute =
  AppProjectsProjectIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdTasksRoute =
  AppProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdRisksRoute =
  AppProjectsProjectIdRisksRouteImport.update({
    id: '/risks',
    path: '/risks',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdQualityRoute =
  AppProjectsProjectIdQualityRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdMilestonesRoute =
  AppProjectsProjectIdMilestonesRouteImport.update({
    id: '/milestones',
    path: '/milestones',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdIssuesRoute =
  AppProjectsProjectIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdEquipmentRoute =
  AppProjectsProjectIdEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDocumentsRoute =
  AppProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDailyLogsRoute =
  AppProjectsProjectIdDailyLogsRouteImport.update({
    id: '/daily-logs',
    path: '/daily-logs',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdAnalyticsRoute =
  AppProjectsProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppHrRecruitmentInterviewsRoute =
  AppHrRecruitmentInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AppHrRecruitmentRoute,
  } as any)
const AppHrPayrollHistoryRoute = AppHrPayrollHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppHrPayrollRoute,
} as any)
const AppHrPayrollApprovalsRoute = AppHrPayrollApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppHrPayrollRoute,
} as any)
const AppHrAttendanceVerificationRoute =
  AppHrAttendanceVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AppHrAttendanceRoute,
  } as any)
const AppHrAttendanceIssuesRoute = AppHrAttendanceIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AppHrAttendanceRoute,
} as any)
const AppHrAttendanceGeofenceRoute = AppHrAttendanceGeofenceRouteImport.update({
  id: '/geofence',
  path: '/geofence',
  getParentRoute: () => AppHrAttendanceRoute,
} as any)
const AppFinanceBudgetsHistoryRoute =
  AppFinanceBudgetsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppFinanceBudgetsComparisonRoute =
  AppFinanceBudgetsComparisonRouteImport.update({
    id: '/comparison',
    path: '/comparison',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppFinanceBudgetsApprovalRoute =
  AppFinanceBudgetsApprovalRouteImport.update({
    id: '/approval',
    path: '/approval',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppFinanceBudgetsAnalyticsRoute =
  AppFinanceBudgetsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppFinanceBudgetsAllocationRoute =
  AppFinanceBudgetsAllocationRouteImport.update({
    id: '/allocation',
    path: '/allocation',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppFinanceBudgetsAdjustmentsRoute =
  AppFinanceBudgetsAdjustmentsRouteImport.update({
    id: '/adjustments',
    path: '/adjustments',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppFinanceBudgetsBudgetIdRoute =
  AppFinanceBudgetsBudgetIdRouteImport.update({
    id: '/$budgetId',
    path: '/$budgetId',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppArchitectRevisionsRevisionIdRoute =
  AppArchitectRevisionsRevisionIdRouteImport.update({
    id: '/$revisionId',
    path: '/$revisionId',
    getParentRoute: () => AppArchitectRevisionsRoute,
  } as any)
const AppArchitectReviewsReviewIdRoute =
  AppArchitectReviewsReviewIdRouteImport.update({
    id: '/$reviewId',
    path: '/$reviewId',
    getParentRoute: () => AppArchitectReviewsRoute,
  } as any)
const AppArchitectDocumentationDocIdRoute =
  AppArchitectDocumentationDocIdRouteImport.update({
    id: '/$docId',
    path: '/$docId',
    getParentRoute: () => AppArchitectDocumentationRoute,
  } as any)
const AppArchitectDesignsNewRoute = AppArchitectDesignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppArchitectDesignsRoute,
} as any)
const AppArchitectDesignsDesignIdRoute =
  AppArchitectDesignsDesignIdRouteImport.update({
    id: '/$designId',
    path: '/$designId',
    getParentRoute: () => AppArchitectDesignsRoute,
  } as any)
const AppArchitectBlueprintsBlueprintIdRoute =
  AppArchitectBlueprintsBlueprintIdRouteImport.update({
    id: '/$blueprintId',
    path: '/$blueprintId',
    getParentRoute: () => AppArchitectBlueprintsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/approvals': typeof AppApprovalsRoute
  '/architect': typeof AppArchitectRouteWithChildren
  '/audit': typeof AppAuditRoute
  '/consultant': typeof AppConsultantRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/engineer': typeof AppEngineerRoute
  '/finance': typeof AppFinanceRouteWithChildren
  '/hr': typeof AppHrRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/resources': typeof AppResourcesRoute
  '/settings': typeof AppSettingsRoute
  '/site': typeof AppSiteRoute
  '/support': typeof AppSupportRoute
  '/workflows': typeof AppWorkflowsRoute
  '/architect/ai': typeof AppArchitectAiRoute
  '/architect/blueprints': typeof AppArchitectBlueprintsRouteWithChildren
  '/architect/designs': typeof AppArchitectDesignsRouteWithChildren
  '/architect/documentation': typeof AppArchitectDocumentationRouteWithChildren
  '/architect/reviews': typeof AppArchitectReviewsRouteWithChildren
  '/architect/revisions': typeof AppArchitectRevisionsRouteWithChildren
  '/finance/ai': typeof AppFinanceAiRoute
  '/finance/approvals': typeof AppFinanceApprovalsRoute
  '/finance/budgets': typeof AppFinanceBudgetsRouteWithChildren
  '/finance/expenses': typeof AppFinanceExpensesRoute
  '/finance/payroll-review': typeof AppFinancePayrollReviewRoute
  '/finance/reports': typeof AppFinanceReportsRoute
  '/hr/ai': typeof AppHrAiRoute
  '/hr/attendance': typeof AppHrAttendanceRouteWithChildren
  '/hr/benefits': typeof AppHrBenefitsRoute
  '/hr/deductions': typeof AppHrDeductionsRoute
  '/hr/documents': typeof AppHrDocumentsRoute
  '/hr/employees': typeof AppHrEmployeesRoute
  '/hr/leave': typeof AppHrLeaveRoute
  '/hr/notifications': typeof AppHrNotificationsRoute
  '/hr/payroll': typeof AppHrPayrollRouteWithChildren
  '/hr/performance': typeof AppHrPerformanceRoute
  '/hr/recruitment': typeof AppHrRecruitmentRouteWithChildren
  '/hr/reports': typeof AppHrReportsRoute
  '/hr/schedule': typeof AppHrScheduleRoute
  '/hr/settings': typeof AppHrSettingsRoute
  '/hr/training': typeof AppHrTrainingRoute
  '/hr/workforce': typeof AppHrWorkforceRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/architect/': typeof AppArchitectIndexRoute
  '/finance/': typeof AppFinanceIndexRoute
  '/architect/blueprints/$blueprintId': typeof AppArchitectBlueprintsBlueprintIdRoute
  '/architect/designs/$designId': typeof AppArchitectDesignsDesignIdRoute
  '/architect/designs/new': typeof AppArchitectDesignsNewRoute
  '/architect/documentation/$docId': typeof AppArchitectDocumentationDocIdRoute
  '/architect/reviews/$reviewId': typeof AppArchitectReviewsReviewIdRoute
  '/architect/revisions/$revisionId': typeof AppArchitectRevisionsRevisionIdRoute
  '/finance/budgets/$budgetId': typeof AppFinanceBudgetsBudgetIdRoute
  '/finance/budgets/adjustments': typeof AppFinanceBudgetsAdjustmentsRoute
  '/finance/budgets/allocation': typeof AppFinanceBudgetsAllocationRoute
  '/finance/budgets/analytics': typeof AppFinanceBudgetsAnalyticsRoute
  '/finance/budgets/approval': typeof AppFinanceBudgetsApprovalRoute
  '/finance/budgets/comparison': typeof AppFinanceBudgetsComparisonRoute
  '/finance/budgets/history': typeof AppFinanceBudgetsHistoryRoute
  '/hr/attendance/geofence': typeof AppHrAttendanceGeofenceRoute
  '/hr/attendance/issues': typeof AppHrAttendanceIssuesRoute
  '/hr/attendance/verification': typeof AppHrAttendanceVerificationRoute
  '/hr/payroll/approvals': typeof AppHrPayrollApprovalsRoute
  '/hr/payroll/history': typeof AppHrPayrollHistoryRoute
  '/hr/recruitment/interviews': typeof AppHrRecruitmentInterviewsRoute
  '/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/daily-logs': typeof AppProjectsProjectIdDailyLogsRoute
  '/projects/$projectId/documents': typeof AppProjectsProjectIdDocumentsRoute
  '/projects/$projectId/equipment': typeof AppProjectsProjectIdEquipmentRoute
  '/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRoute
  '/projects/$projectId/milestones': typeof AppProjectsProjectIdMilestonesRoute
  '/projects/$projectId/quality': typeof AppProjectsProjectIdQualityRoute
  '/projects/$projectId/risks': typeof AppProjectsProjectIdRisksRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/projects/$projectId/timeline': typeof AppProjectsProjectIdTimelineRoute
  '/projects/$projectId/workforce': typeof AppProjectsProjectIdWorkforceRoute
  '/architect/blueprints/': typeof AppArchitectBlueprintsIndexRoute
  '/architect/designs/': typeof AppArchitectDesignsIndexRoute
  '/architect/documentation/': typeof AppArchitectDocumentationIndexRoute
  '/architect/reviews/': typeof AppArchitectReviewsIndexRoute
  '/architect/revisions/': typeof AppArchitectRevisionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/consultant': typeof AppConsultantRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/engineer': typeof AppEngineerRoute
  '/hr': typeof AppHrRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/resources': typeof AppResourcesRoute
  '/settings': typeof AppSettingsRoute
  '/site': typeof AppSiteRoute
  '/support': typeof AppSupportRoute
  '/workflows': typeof AppWorkflowsRoute
  '/architect/ai': typeof AppArchitectAiRoute
  '/finance/ai': typeof AppFinanceAiRoute
  '/finance/approvals': typeof AppFinanceApprovalsRoute
  '/finance/budgets': typeof AppFinanceBudgetsRouteWithChildren
  '/finance/expenses': typeof AppFinanceExpensesRoute
  '/finance/payroll-review': typeof AppFinancePayrollReviewRoute
  '/finance/reports': typeof AppFinanceReportsRoute
  '/hr/ai': typeof AppHrAiRoute
  '/hr/attendance': typeof AppHrAttendanceRouteWithChildren
  '/hr/benefits': typeof AppHrBenefitsRoute
  '/hr/deductions': typeof AppHrDeductionsRoute
  '/hr/documents': typeof AppHrDocumentsRoute
  '/hr/employees': typeof AppHrEmployeesRoute
  '/hr/leave': typeof AppHrLeaveRoute
  '/hr/notifications': typeof AppHrNotificationsRoute
  '/hr/payroll': typeof AppHrPayrollRouteWithChildren
  '/hr/performance': typeof AppHrPerformanceRoute
  '/hr/recruitment': typeof AppHrRecruitmentRouteWithChildren
  '/hr/reports': typeof AppHrReportsRoute
  '/hr/schedule': typeof AppHrScheduleRoute
  '/hr/settings': typeof AppHrSettingsRoute
  '/hr/training': typeof AppHrTrainingRoute
  '/hr/workforce': typeof AppHrWorkforceRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/architect': typeof AppArchitectIndexRoute
  '/finance': typeof AppFinanceIndexRoute
  '/architect/blueprints/$blueprintId': typeof AppArchitectBlueprintsBlueprintIdRoute
  '/architect/designs/$designId': typeof AppArchitectDesignsDesignIdRoute
  '/architect/designs/new': typeof AppArchitectDesignsNewRoute
  '/architect/documentation/$docId': typeof AppArchitectDocumentationDocIdRoute
  '/architect/reviews/$reviewId': typeof AppArchitectReviewsReviewIdRoute
  '/architect/revisions/$revisionId': typeof AppArchitectRevisionsRevisionIdRoute
  '/finance/budgets/$budgetId': typeof AppFinanceBudgetsBudgetIdRoute
  '/finance/budgets/adjustments': typeof AppFinanceBudgetsAdjustmentsRoute
  '/finance/budgets/allocation': typeof AppFinanceBudgetsAllocationRoute
  '/finance/budgets/analytics': typeof AppFinanceBudgetsAnalyticsRoute
  '/finance/budgets/approval': typeof AppFinanceBudgetsApprovalRoute
  '/finance/budgets/comparison': typeof AppFinanceBudgetsComparisonRoute
  '/finance/budgets/history': typeof AppFinanceBudgetsHistoryRoute
  '/hr/attendance/geofence': typeof AppHrAttendanceGeofenceRoute
  '/hr/attendance/issues': typeof AppHrAttendanceIssuesRoute
  '/hr/attendance/verification': typeof AppHrAttendanceVerificationRoute
  '/hr/payroll/approvals': typeof AppHrPayrollApprovalsRoute
  '/hr/payroll/history': typeof AppHrPayrollHistoryRoute
  '/hr/recruitment/interviews': typeof AppHrRecruitmentInterviewsRoute
  '/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/daily-logs': typeof AppProjectsProjectIdDailyLogsRoute
  '/projects/$projectId/documents': typeof AppProjectsProjectIdDocumentsRoute
  '/projects/$projectId/equipment': typeof AppProjectsProjectIdEquipmentRoute
  '/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRoute
  '/projects/$projectId/milestones': typeof AppProjectsProjectIdMilestonesRoute
  '/projects/$projectId/quality': typeof AppProjectsProjectIdQualityRoute
  '/projects/$projectId/risks': typeof AppProjectsProjectIdRisksRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/projects/$projectId/timeline': typeof AppProjectsProjectIdTimelineRoute
  '/projects/$projectId/workforce': typeof AppProjectsProjectIdWorkforceRoute
  '/architect/blueprints': typeof AppArchitectBlueprintsIndexRoute
  '/architect/designs': typeof AppArchitectDesignsIndexRoute
  '/architect/documentation': typeof AppArchitectDocumentationIndexRoute
  '/architect/reviews': typeof AppArchitectReviewsIndexRoute
  '/architect/revisions': typeof AppArchitectRevisionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-insights': typeof AppAiInsightsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/architect': typeof AppArchitectRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/consultant': typeof AppConsultantRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/engineer': typeof AppEngineerRoute
  '/_app/finance': typeof AppFinanceRouteWithChildren
  '/_app/hr': typeof AppHrRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/site': typeof AppSiteRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/workflows': typeof AppWorkflowsRoute
  '/_app/architect/ai': typeof AppArchitectAiRoute
  '/_app/architect/blueprints': typeof AppArchitectBlueprintsRouteWithChildren
  '/_app/architect/designs': typeof AppArchitectDesignsRouteWithChildren
  '/_app/architect/documentation': typeof AppArchitectDocumentationRouteWithChildren
  '/_app/architect/reviews': typeof AppArchitectReviewsRouteWithChildren
  '/_app/architect/revisions': typeof AppArchitectRevisionsRouteWithChildren
  '/_app/finance/ai': typeof AppFinanceAiRoute
  '/_app/finance/approvals': typeof AppFinanceApprovalsRoute
  '/_app/finance/budgets': typeof AppFinanceBudgetsRouteWithChildren
  '/_app/finance/expenses': typeof AppFinanceExpensesRoute
  '/_app/finance/payroll-review': typeof AppFinancePayrollReviewRoute
  '/_app/finance/reports': typeof AppFinanceReportsRoute
  '/_app/hr/ai': typeof AppHrAiRoute
  '/_app/hr/attendance': typeof AppHrAttendanceRouteWithChildren
  '/_app/hr/benefits': typeof AppHrBenefitsRoute
  '/_app/hr/deductions': typeof AppHrDeductionsRoute
  '/_app/hr/documents': typeof AppHrDocumentsRoute
  '/_app/hr/employees': typeof AppHrEmployeesRoute
  '/_app/hr/leave': typeof AppHrLeaveRoute
  '/_app/hr/notifications': typeof AppHrNotificationsRoute
  '/_app/hr/payroll': typeof AppHrPayrollRouteWithChildren
  '/_app/hr/performance': typeof AppHrPerformanceRoute
  '/_app/hr/recruitment': typeof AppHrRecruitmentRouteWithChildren
  '/_app/hr/reports': typeof AppHrReportsRoute
  '/_app/hr/schedule': typeof AppHrScheduleRoute
  '/_app/hr/settings': typeof AppHrSettingsRoute
  '/_app/hr/training': typeof AppHrTrainingRoute
  '/_app/hr/workforce': typeof AppHrWorkforceRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/architect/': typeof AppArchitectIndexRoute
  '/_app/finance/': typeof AppFinanceIndexRoute
  '/_app/architect/blueprints/$blueprintId': typeof AppArchitectBlueprintsBlueprintIdRoute
  '/_app/architect/designs/$designId': typeof AppArchitectDesignsDesignIdRoute
  '/_app/architect/designs/new': typeof AppArchitectDesignsNewRoute
  '/_app/architect/documentation/$docId': typeof AppArchitectDocumentationDocIdRoute
  '/_app/architect/reviews/$reviewId': typeof AppArchitectReviewsReviewIdRoute
  '/_app/architect/revisions/$revisionId': typeof AppArchitectRevisionsRevisionIdRoute
  '/_app/finance/budgets/$budgetId': typeof AppFinanceBudgetsBudgetIdRoute
  '/_app/finance/budgets/adjustments': typeof AppFinanceBudgetsAdjustmentsRoute
  '/_app/finance/budgets/allocation': typeof AppFinanceBudgetsAllocationRoute
  '/_app/finance/budgets/analytics': typeof AppFinanceBudgetsAnalyticsRoute
  '/_app/finance/budgets/approval': typeof AppFinanceBudgetsApprovalRoute
  '/_app/finance/budgets/comparison': typeof AppFinanceBudgetsComparisonRoute
  '/_app/finance/budgets/history': typeof AppFinanceBudgetsHistoryRoute
  '/_app/hr/attendance/geofence': typeof AppHrAttendanceGeofenceRoute
  '/_app/hr/attendance/issues': typeof AppHrAttendanceIssuesRoute
  '/_app/hr/attendance/verification': typeof AppHrAttendanceVerificationRoute
  '/_app/hr/payroll/approvals': typeof AppHrPayrollApprovalsRoute
  '/_app/hr/payroll/history': typeof AppHrPayrollHistoryRoute
  '/_app/hr/recruitment/interviews': typeof AppHrRecruitmentInterviewsRoute
  '/_app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/_app/projects/$projectId/daily-logs': typeof AppProjectsProjectIdDailyLogsRoute
  '/_app/projects/$projectId/documents': typeof AppProjectsProjectIdDocumentsRoute
  '/_app/projects/$projectId/equipment': typeof AppProjectsProjectIdEquipmentRoute
  '/_app/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRoute
  '/_app/projects/$projectId/milestones': typeof AppProjectsProjectIdMilestonesRoute
  '/_app/projects/$projectId/quality': typeof AppProjectsProjectIdQualityRoute
  '/_app/projects/$projectId/risks': typeof AppProjectsProjectIdRisksRoute
  '/_app/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/_app/projects/$projectId/timeline': typeof AppProjectsProjectIdTimelineRoute
  '/_app/projects/$projectId/workforce': typeof AppProjectsProjectIdWorkforceRoute
  '/_app/architect/blueprints/': typeof AppArchitectBlueprintsIndexRoute
  '/_app/architect/designs/': typeof AppArchitectDesignsIndexRoute
  '/_app/architect/documentation/': typeof AppArchitectDocumentationIndexRoute
  '/_app/architect/reviews/': typeof AppArchitectReviewsIndexRoute
  '/_app/architect/revisions/': typeof AppArchitectRevisionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/approvals'
    | '/architect'
    | '/audit'
    | '/consultant'
    | '/dashboard'
    | '/documents'
    | '/engineer'
    | '/finance'
    | '/hr'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/site'
    | '/support'
    | '/workflows'
    | '/architect/ai'
    | '/architect/blueprints'
    | '/architect/designs'
    | '/architect/documentation'
    | '/architect/reviews'
    | '/architect/revisions'
    | '/finance/ai'
    | '/finance/approvals'
    | '/finance/budgets'
    | '/finance/expenses'
    | '/finance/payroll-review'
    | '/finance/reports'
    | '/hr/ai'
    | '/hr/attendance'
    | '/hr/benefits'
    | '/hr/deductions'
    | '/hr/documents'
    | '/hr/employees'
    | '/hr/leave'
    | '/hr/notifications'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/recruitment'
    | '/hr/reports'
    | '/hr/schedule'
    | '/hr/settings'
    | '/hr/training'
    | '/hr/workforce'
    | '/projects/$projectId'
    | '/projects/new'
    | '/architect/'
    | '/finance/'
    | '/architect/blueprints/$blueprintId'
    | '/architect/designs/$designId'
    | '/architect/designs/new'
    | '/architect/documentation/$docId'
    | '/architect/reviews/$reviewId'
    | '/architect/revisions/$revisionId'
    | '/finance/budgets/$budgetId'
    | '/finance/budgets/adjustments'
    | '/finance/budgets/allocation'
    | '/finance/budgets/analytics'
    | '/finance/budgets/approval'
    | '/finance/budgets/comparison'
    | '/finance/budgets/history'
    | '/hr/attendance/geofence'
    | '/hr/attendance/issues'
    | '/hr/attendance/verification'
    | '/hr/payroll/approvals'
    | '/hr/payroll/history'
    | '/hr/recruitment/interviews'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/daily-logs'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/equipment'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/milestones'
    | '/projects/$projectId/quality'
    | '/projects/$projectId/risks'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId/workforce'
    | '/architect/blueprints/'
    | '/architect/designs/'
    | '/architect/documentation/'
    | '/architect/reviews/'
    | '/architect/revisions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/approvals'
    | '/audit'
    | '/consultant'
    | '/dashboard'
    | '/documents'
    | '/engineer'
    | '/hr'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/site'
    | '/support'
    | '/workflows'
    | '/architect/ai'
    | '/finance/ai'
    | '/finance/approvals'
    | '/finance/budgets'
    | '/finance/expenses'
    | '/finance/payroll-review'
    | '/finance/reports'
    | '/hr/ai'
    | '/hr/attendance'
    | '/hr/benefits'
    | '/hr/deductions'
    | '/hr/documents'
    | '/hr/employees'
    | '/hr/leave'
    | '/hr/notifications'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/recruitment'
    | '/hr/reports'
    | '/hr/schedule'
    | '/hr/settings'
    | '/hr/training'
    | '/hr/workforce'
    | '/projects/$projectId'
    | '/projects/new'
    | '/architect'
    | '/finance'
    | '/architect/blueprints/$blueprintId'
    | '/architect/designs/$designId'
    | '/architect/designs/new'
    | '/architect/documentation/$docId'
    | '/architect/reviews/$reviewId'
    | '/architect/revisions/$revisionId'
    | '/finance/budgets/$budgetId'
    | '/finance/budgets/adjustments'
    | '/finance/budgets/allocation'
    | '/finance/budgets/analytics'
    | '/finance/budgets/approval'
    | '/finance/budgets/comparison'
    | '/finance/budgets/history'
    | '/hr/attendance/geofence'
    | '/hr/attendance/issues'
    | '/hr/attendance/verification'
    | '/hr/payroll/approvals'
    | '/hr/payroll/history'
    | '/hr/recruitment/interviews'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/daily-logs'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/equipment'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/milestones'
    | '/projects/$projectId/quality'
    | '/projects/$projectId/risks'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId/workforce'
    | '/architect/blueprints'
    | '/architect/designs'
    | '/architect/documentation'
    | '/architect/reviews'
    | '/architect/revisions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/ai-insights'
    | '/_app/approvals'
    | '/_app/architect'
    | '/_app/audit'
    | '/_app/consultant'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/engineer'
    | '/_app/finance'
    | '/_app/hr'
    | '/_app/notifications'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/resources'
    | '/_app/settings'
    | '/_app/site'
    | '/_app/support'
    | '/_app/workflows'
    | '/_app/architect/ai'
    | '/_app/architect/blueprints'
    | '/_app/architect/designs'
    | '/_app/architect/documentation'
    | '/_app/architect/reviews'
    | '/_app/architect/revisions'
    | '/_app/finance/ai'
    | '/_app/finance/approvals'
    | '/_app/finance/budgets'
    | '/_app/finance/expenses'
    | '/_app/finance/payroll-review'
    | '/_app/finance/reports'
    | '/_app/hr/ai'
    | '/_app/hr/attendance'
    | '/_app/hr/benefits'
    | '/_app/hr/deductions'
    | '/_app/hr/documents'
    | '/_app/hr/employees'
    | '/_app/hr/leave'
    | '/_app/hr/notifications'
    | '/_app/hr/payroll'
    | '/_app/hr/performance'
    | '/_app/hr/recruitment'
    | '/_app/hr/reports'
    | '/_app/hr/schedule'
    | '/_app/hr/settings'
    | '/_app/hr/training'
    | '/_app/hr/workforce'
    | '/_app/projects/$projectId'
    | '/_app/projects/new'
    | '/_app/architect/'
    | '/_app/finance/'
    | '/_app/architect/blueprints/$blueprintId'
    | '/_app/architect/designs/$designId'
    | '/_app/architect/designs/new'
    | '/_app/architect/documentation/$docId'
    | '/_app/architect/reviews/$reviewId'
    | '/_app/architect/revisions/$revisionId'
    | '/_app/finance/budgets/$budgetId'
    | '/_app/finance/budgets/adjustments'
    | '/_app/finance/budgets/allocation'
    | '/_app/finance/budgets/analytics'
    | '/_app/finance/budgets/approval'
    | '/_app/finance/budgets/comparison'
    | '/_app/finance/budgets/history'
    | '/_app/hr/attendance/geofence'
    | '/_app/hr/attendance/issues'
    | '/_app/hr/attendance/verification'
    | '/_app/hr/payroll/approvals'
    | '/_app/hr/payroll/history'
    | '/_app/hr/recruitment/interviews'
    | '/_app/projects/$projectId/analytics'
    | '/_app/projects/$projectId/daily-logs'
    | '/_app/projects/$projectId/documents'
    | '/_app/projects/$projectId/equipment'
    | '/_app/projects/$projectId/issues'
    | '/_app/projects/$projectId/milestones'
    | '/_app/projects/$projectId/quality'
    | '/_app/projects/$projectId/risks'
    | '/_app/projects/$projectId/tasks'
    | '/_app/projects/$projectId/timeline'
    | '/_app/projects/$projectId/workforce'
    | '/_app/architect/blueprints/'
    | '/_app/architect/designs/'
    | '/_app/architect/documentation/'
    | '/_app/architect/reviews/'
    | '/_app/architect/revisions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/site': {
      id: '/_app/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof AppSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/engineer': {
      id: '/_app/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof AppEngineerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultant': {
      id: '/_app/consultant'
      path: '/consultant'
      fullPath: '/consultant'
      preLoaderRoute: typeof AppConsultantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/architect': {
      id: '/_app/architect'
      path: '/architect'
      fullPath: '/architect'
      preLoaderRoute: typeof AppArchitectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-insights': {
      id: '/_app/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/': {
      id: '/_app/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/architect/': {
      id: '/_app/architect/'
      path: '/'
      fullPath: '/architect/'
      preLoaderRoute: typeof AppArchitectIndexRouteImport
      parentRoute: typeof AppArchitectRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/hr/workforce': {
      id: '/_app/hr/workforce'
      path: '/workforce'
      fullPath: '/hr/workforce'
      preLoaderRoute: typeof AppHrWorkforceRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/training': {
      id: '/_app/hr/training'
      path: '/training'
      fullPath: '/hr/training'
      preLoaderRoute: typeof AppHrTrainingRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/settings': {
      id: '/_app/hr/settings'
      path: '/settings'
      fullPath: '/hr/settings'
      preLoaderRoute: typeof AppHrSettingsRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/schedule': {
      id: '/_app/hr/schedule'
      path: '/schedule'
      fullPath: '/hr/schedule'
      preLoaderRoute: typeof AppHrScheduleRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/reports': {
      id: '/_app/hr/reports'
      path: '/reports'
      fullPath: '/hr/reports'
      preLoaderRoute: typeof AppHrReportsRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/recruitment': {
      id: '/_app/hr/recruitment'
      path: '/recruitment'
      fullPath: '/hr/recruitment'
      preLoaderRoute: typeof AppHrRecruitmentRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/performance': {
      id: '/_app/hr/performance'
      path: '/performance'
      fullPath: '/hr/performance'
      preLoaderRoute: typeof AppHrPerformanceRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/payroll': {
      id: '/_app/hr/payroll'
      path: '/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AppHrPayrollRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/notifications': {
      id: '/_app/hr/notifications'
      path: '/notifications'
      fullPath: '/hr/notifications'
      preLoaderRoute: typeof AppHrNotificationsRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/leave': {
      id: '/_app/hr/leave'
      path: '/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof AppHrLeaveRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/employees': {
      id: '/_app/hr/employees'
      path: '/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof AppHrEmployeesRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/documents': {
      id: '/_app/hr/documents'
      path: '/documents'
      fullPath: '/hr/documents'
      preLoaderRoute: typeof AppHrDocumentsRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/deductions': {
      id: '/_app/hr/deductions'
      path: '/deductions'
      fullPath: '/hr/deductions'
      preLoaderRoute: typeof AppHrDeductionsRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/benefits': {
      id: '/_app/hr/benefits'
      path: '/benefits'
      fullPath: '/hr/benefits'
      preLoaderRoute: typeof AppHrBenefitsRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/attendance': {
      id: '/_app/hr/attendance'
      path: '/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AppHrAttendanceRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/ai': {
      id: '/_app/hr/ai'
      path: '/ai'
      fullPath: '/hr/ai'
      preLoaderRoute: typeof AppHrAiRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/finance/reports': {
      id: '/_app/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof AppFinanceReportsRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/finance/payroll-review': {
      id: '/_app/finance/payroll-review'
      path: '/payroll-review'
      fullPath: '/finance/payroll-review'
      preLoaderRoute: typeof AppFinancePayrollReviewRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/finance/expenses': {
      id: '/_app/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof AppFinanceExpensesRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/finance/budgets': {
      id: '/_app/finance/budgets'
      path: '/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof AppFinanceBudgetsRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/finance/approvals': {
      id: '/_app/finance/approvals'
      path: '/approvals'
      fullPath: '/finance/approvals'
      preLoaderRoute: typeof AppFinanceApprovalsRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/finance/ai': {
      id: '/_app/finance/ai'
      path: '/ai'
      fullPath: '/finance/ai'
      preLoaderRoute: typeof AppFinanceAiRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/architect/revisions': {
      id: '/_app/architect/revisions'
      path: '/revisions'
      fullPath: '/architect/revisions'
      preLoaderRoute: typeof AppArchitectRevisionsRouteImport
      parentRoute: typeof AppArchitectRoute
    }
    '/_app/architect/reviews': {
      id: '/_app/architect/reviews'
      path: '/reviews'
      fullPath: '/architect/reviews'
      preLoaderRoute: typeof AppArchitectReviewsRouteImport
      parentRoute: typeof AppArchitectRoute
    }
    '/_app/architect/documentation': {
      id: '/_app/architect/documentation'
      path: '/documentation'
      fullPath: '/architect/documentation'
      preLoaderRoute: typeof AppArchitectDocumentationRouteImport
      parentRoute: typeof AppArchitectRoute
    }
    '/_app/architect/designs': {
      id: '/_app/architect/designs'
      path: '/designs'
      fullPath: '/architect/designs'
      preLoaderRoute: typeof AppArchitectDesignsRouteImport
      parentRoute: typeof AppArchitectRoute
    }
    '/_app/architect/blueprints': {
      id: '/_app/architect/blueprints'
      path: '/blueprints'
      fullPath: '/architect/blueprints'
      preLoaderRoute: typeof AppArchitectBlueprintsRouteImport
      parentRoute: typeof AppArchitectRoute
    }
    '/_app/architect/ai': {
      id: '/_app/architect/ai'
      path: '/ai'
      fullPath: '/architect/ai'
      preLoaderRoute: typeof AppArchitectAiRouteImport
      parentRoute: typeof AppArchitectRoute
    }
    '/_app/architect/revisions/': {
      id: '/_app/architect/revisions/'
      path: '/'
      fullPath: '/architect/revisions/'
      preLoaderRoute: typeof AppArchitectRevisionsIndexRouteImport
      parentRoute: typeof AppArchitectRevisionsRoute
    }
    '/_app/architect/reviews/': {
      id: '/_app/architect/reviews/'
      path: '/'
      fullPath: '/architect/reviews/'
      preLoaderRoute: typeof AppArchitectReviewsIndexRouteImport
      parentRoute: typeof AppArchitectReviewsRoute
    }
    '/_app/architect/documentation/': {
      id: '/_app/architect/documentation/'
      path: '/'
      fullPath: '/architect/documentation/'
      preLoaderRoute: typeof AppArchitectDocumentationIndexRouteImport
      parentRoute: typeof AppArchitectDocumentationRoute
    }
    '/_app/architect/designs/': {
      id: '/_app/architect/designs/'
      path: '/'
      fullPath: '/architect/designs/'
      preLoaderRoute: typeof AppArchitectDesignsIndexRouteImport
      parentRoute: typeof AppArchitectDesignsRoute
    }
    '/_app/architect/blueprints/': {
      id: '/_app/architect/blueprints/'
      path: '/'
      fullPath: '/architect/blueprints/'
      preLoaderRoute: typeof AppArchitectBlueprintsIndexRouteImport
      parentRoute: typeof AppArchitectBlueprintsRoute
    }
    '/_app/projects/$projectId/workforce': {
      id: '/_app/projects/$projectId/workforce'
      path: '/workforce'
      fullPath: '/projects/$projectId/workforce'
      preLoaderRoute: typeof AppProjectsProjectIdWorkforceRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/timeline': {
      id: '/_app/projects/$projectId/timeline'
      path: '/timeline'
      fullPath: '/projects/$projectId/timeline'
      preLoaderRoute: typeof AppProjectsProjectIdTimelineRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/tasks': {
      id: '/_app/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof AppProjectsProjectIdTasksRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/risks': {
      id: '/_app/projects/$projectId/risks'
      path: '/risks'
      fullPath: '/projects/$projectId/risks'
      preLoaderRoute: typeof AppProjectsProjectIdRisksRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/quality': {
      id: '/_app/projects/$projectId/quality'
      path: '/quality'
      fullPath: '/projects/$projectId/quality'
      preLoaderRoute: typeof AppProjectsProjectIdQualityRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/milestones': {
      id: '/_app/projects/$projectId/milestones'
      path: '/milestones'
      fullPath: '/projects/$projectId/milestones'
      preLoaderRoute: typeof AppProjectsProjectIdMilestonesRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/issues': {
      id: '/_app/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/equipment': {
      id: '/_app/projects/$projectId/equipment'
      path: '/equipment'
      fullPath: '/projects/$projectId/equipment'
      preLoaderRoute: typeof AppProjectsProjectIdEquipmentRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/documents': {
      id: '/_app/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof AppProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/daily-logs': {
      id: '/_app/projects/$projectId/daily-logs'
      path: '/daily-logs'
      fullPath: '/projects/$projectId/daily-logs'
      preLoaderRoute: typeof AppProjectsProjectIdDailyLogsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/analytics': {
      id: '/_app/projects/$projectId/analytics'
      path: '/analytics'
      fullPath: '/projects/$projectId/analytics'
      preLoaderRoute: typeof AppProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/hr/recruitment/interviews': {
      id: '/_app/hr/recruitment/interviews'
      path: '/interviews'
      fullPath: '/hr/recruitment/interviews'
      preLoaderRoute: typeof AppHrRecruitmentInterviewsRouteImport
      parentRoute: typeof AppHrRecruitmentRoute
    }
    '/_app/hr/payroll/history': {
      id: '/_app/hr/payroll/history'
      path: '/history'
      fullPath: '/hr/payroll/history'
      preLoaderRoute: typeof AppHrPayrollHistoryRouteImport
      parentRoute: typeof AppHrPayrollRoute
    }
    '/_app/hr/payroll/approvals': {
      id: '/_app/hr/payroll/approvals'
      path: '/approvals'
      fullPath: '/hr/payroll/approvals'
      preLoaderRoute: typeof AppHrPayrollApprovalsRouteImport
      parentRoute: typeof AppHrPayrollRoute
    }
    '/_app/hr/attendance/verification': {
      id: '/_app/hr/attendance/verification'
      path: '/verification'
      fullPath: '/hr/attendance/verification'
      preLoaderRoute: typeof AppHrAttendanceVerificationRouteImport
      parentRoute: typeof AppHrAttendanceRoute
    }
    '/_app/hr/attendance/issues': {
      id: '/_app/hr/attendance/issues'
      path: '/issues'
      fullPath: '/hr/attendance/issues'
      preLoaderRoute: typeof AppHrAttendanceIssuesRouteImport
      parentRoute: typeof AppHrAttendanceRoute
    }
    '/_app/hr/attendance/geofence': {
      id: '/_app/hr/attendance/geofence'
      path: '/geofence'
      fullPath: '/hr/attendance/geofence'
      preLoaderRoute: typeof AppHrAttendanceGeofenceRouteImport
      parentRoute: typeof AppHrAttendanceRoute
    }
    '/_app/finance/budgets/history': {
      id: '/_app/finance/budgets/history'
      path: '/history'
      fullPath: '/finance/budgets/history'
      preLoaderRoute: typeof AppFinanceBudgetsHistoryRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/finance/budgets/comparison': {
      id: '/_app/finance/budgets/comparison'
      path: '/comparison'
      fullPath: '/finance/budgets/comparison'
      preLoaderRoute: typeof AppFinanceBudgetsComparisonRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/finance/budgets/approval': {
      id: '/_app/finance/budgets/approval'
      path: '/approval'
      fullPath: '/finance/budgets/approval'
      preLoaderRoute: typeof AppFinanceBudgetsApprovalRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/finance/budgets/analytics': {
      id: '/_app/finance/budgets/analytics'
      path: '/analytics'
      fullPath: '/finance/budgets/analytics'
      preLoaderRoute: typeof AppFinanceBudgetsAnalyticsRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/finance/budgets/allocation': {
      id: '/_app/finance/budgets/allocation'
      path: '/allocation'
      fullPath: '/finance/budgets/allocation'
      preLoaderRoute: typeof AppFinanceBudgetsAllocationRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/finance/budgets/adjustments': {
      id: '/_app/finance/budgets/adjustments'
      path: '/adjustments'
      fullPath: '/finance/budgets/adjustments'
      preLoaderRoute: typeof AppFinanceBudgetsAdjustmentsRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/finance/budgets/$budgetId': {
      id: '/_app/finance/budgets/$budgetId'
      path: '/$budgetId'
      fullPath: '/finance/budgets/$budgetId'
      preLoaderRoute: typeof AppFinanceBudgetsBudgetIdRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/architect/revisions/$revisionId': {
      id: '/_app/architect/revisions/$revisionId'
      path: '/$revisionId'
      fullPath: '/architect/revisions/$revisionId'
      preLoaderRoute: typeof AppArchitectRevisionsRevisionIdRouteImport
      parentRoute: typeof AppArchitectRevisionsRoute
    }
    '/_app/architect/reviews/$reviewId': {
      id: '/_app/architect/reviews/$reviewId'
      path: '/$reviewId'
      fullPath: '/architect/reviews/$reviewId'
      preLoaderRoute: typeof AppArchitectReviewsReviewIdRouteImport
      parentRoute: typeof AppArchitectReviewsRoute
    }
    '/_app/architect/documentation/$docId': {
      id: '/_app/architect/documentation/$docId'
      path: '/$docId'
      fullPath: '/architect/documentation/$docId'
      preLoaderRoute: typeof AppArchitectDocumentationDocIdRouteImport
      parentRoute: typeof AppArchitectDocumentationRoute
    }
    '/_app/architect/designs/new': {
      id: '/_app/architect/designs/new'
      path: '/new'
      fullPath: '/architect/designs/new'
      preLoaderRoute: typeof AppArchitectDesignsNewRouteImport
      parentRoute: typeof AppArchitectDesignsRoute
    }
    '/_app/architect/designs/$designId': {
      id: '/_app/architect/designs/$designId'
      path: '/$designId'
      fullPath: '/architect/designs/$designId'
      preLoaderRoute: typeof AppArchitectDesignsDesignIdRouteImport
      parentRoute: typeof AppArchitectDesignsRoute
    }
    '/_app/architect/blueprints/$blueprintId': {
      id: '/_app/architect/blueprints/$blueprintId'
      path: '/$blueprintId'
      fullPath: '/architect/blueprints/$blueprintId'
      preLoaderRoute: typeof AppArchitectBlueprintsBlueprintIdRouteImport
      parentRoute: typeof AppArchitectBlueprintsRoute
    }
  }
}

interface AppArchitectBlueprintsRouteChildren {
  AppArchitectBlueprintsBlueprintIdRoute: typeof AppArchitectBlueprintsBlueprintIdRoute
  AppArchitectBlueprintsIndexRoute: typeof AppArchitectBlueprintsIndexRoute
}

const AppArchitectBlueprintsRouteChildren: AppArchitectBlueprintsRouteChildren =
  {
    AppArchitectBlueprintsBlueprintIdRoute:
      AppArchitectBlueprintsBlueprintIdRoute,
    AppArchitectBlueprintsIndexRoute: AppArchitectBlueprintsIndexRoute,
  }

const AppArchitectBlueprintsRouteWithChildren =
  AppArchitectBlueprintsRoute._addFileChildren(
    AppArchitectBlueprintsRouteChildren,
  )

interface AppArchitectDesignsRouteChildren {
  AppArchitectDesignsDesignIdRoute: typeof AppArchitectDesignsDesignIdRoute
  AppArchitectDesignsNewRoute: typeof AppArchitectDesignsNewRoute
  AppArchitectDesignsIndexRoute: typeof AppArchitectDesignsIndexRoute
}

const AppArchitectDesignsRouteChildren: AppArchitectDesignsRouteChildren = {
  AppArchitectDesignsDesignIdRoute: AppArchitectDesignsDesignIdRoute,
  AppArchitectDesignsNewRoute: AppArchitectDesignsNewRoute,
  AppArchitectDesignsIndexRoute: AppArchitectDesignsIndexRoute,
}

const AppArchitectDesignsRouteWithChildren =
  AppArchitectDesignsRoute._addFileChildren(AppArchitectDesignsRouteChildren)

interface AppArchitectDocumentationRouteChildren {
  AppArchitectDocumentationDocIdRoute: typeof AppArchitectDocumentationDocIdRoute
  AppArchitectDocumentationIndexRoute: typeof AppArchitectDocumentationIndexRoute
}

const AppArchitectDocumentationRouteChildren: AppArchitectDocumentationRouteChildren =
  {
    AppArchitectDocumentationDocIdRoute: AppArchitectDocumentationDocIdRoute,
    AppArchitectDocumentationIndexRoute: AppArchitectDocumentationIndexRoute,
  }

const AppArchitectDocumentationRouteWithChildren =
  AppArchitectDocumentationRoute._addFileChildren(
    AppArchitectDocumentationRouteChildren,
  )

interface AppArchitectReviewsRouteChildren {
  AppArchitectReviewsReviewIdRoute: typeof AppArchitectReviewsReviewIdRoute
  AppArchitectReviewsIndexRoute: typeof AppArchitectReviewsIndexRoute
}

const AppArchitectReviewsRouteChildren: AppArchitectReviewsRouteChildren = {
  AppArchitectReviewsReviewIdRoute: AppArchitectReviewsReviewIdRoute,
  AppArchitectReviewsIndexRoute: AppArchitectReviewsIndexRoute,
}

const AppArchitectReviewsRouteWithChildren =
  AppArchitectReviewsRoute._addFileChildren(AppArchitectReviewsRouteChildren)

interface AppArchitectRevisionsRouteChildren {
  AppArchitectRevisionsRevisionIdRoute: typeof AppArchitectRevisionsRevisionIdRoute
  AppArchitectRevisionsIndexRoute: typeof AppArchitectRevisionsIndexRoute
}

const AppArchitectRevisionsRouteChildren: AppArchitectRevisionsRouteChildren = {
  AppArchitectRevisionsRevisionIdRoute: AppArchitectRevisionsRevisionIdRoute,
  AppArchitectRevisionsIndexRoute: AppArchitectRevisionsIndexRoute,
}

const AppArchitectRevisionsRouteWithChildren =
  AppArchitectRevisionsRoute._addFileChildren(
    AppArchitectRevisionsRouteChildren,
  )

interface AppArchitectRouteChildren {
  AppArchitectAiRoute: typeof AppArchitectAiRoute
  AppArchitectBlueprintsRoute: typeof AppArchitectBlueprintsRouteWithChildren
  AppArchitectDesignsRoute: typeof AppArchitectDesignsRouteWithChildren
  AppArchitectDocumentationRoute: typeof AppArchitectDocumentationRouteWithChildren
  AppArchitectReviewsRoute: typeof AppArchitectReviewsRouteWithChildren
  AppArchitectRevisionsRoute: typeof AppArchitectRevisionsRouteWithChildren
  AppArchitectIndexRoute: typeof AppArchitectIndexRoute
}

const AppArchitectRouteChildren: AppArchitectRouteChildren = {
  AppArchitectAiRoute: AppArchitectAiRoute,
  AppArchitectBlueprintsRoute: AppArchitectBlueprintsRouteWithChildren,
  AppArchitectDesignsRoute: AppArchitectDesignsRouteWithChildren,
  AppArchitectDocumentationRoute: AppArchitectDocumentationRouteWithChildren,
  AppArchitectReviewsRoute: AppArchitectReviewsRouteWithChildren,
  AppArchitectRevisionsRoute: AppArchitectRevisionsRouteWithChildren,
  AppArchitectIndexRoute: AppArchitectIndexRoute,
}

const AppArchitectRouteWithChildren = AppArchitectRoute._addFileChildren(
  AppArchitectRouteChildren,
)

interface AppFinanceBudgetsRouteChildren {
  AppFinanceBudgetsBudgetIdRoute: typeof AppFinanceBudgetsBudgetIdRoute
  AppFinanceBudgetsAdjustmentsRoute: typeof AppFinanceBudgetsAdjustmentsRoute
  AppFinanceBudgetsAllocationRoute: typeof AppFinanceBudgetsAllocationRoute
  AppFinanceBudgetsAnalyticsRoute: typeof AppFinanceBudgetsAnalyticsRoute
  AppFinanceBudgetsApprovalRoute: typeof AppFinanceBudgetsApprovalRoute
  AppFinanceBudgetsComparisonRoute: typeof AppFinanceBudgetsComparisonRoute
  AppFinanceBudgetsHistoryRoute: typeof AppFinanceBudgetsHistoryRoute
}

const AppFinanceBudgetsRouteChildren: AppFinanceBudgetsRouteChildren = {
  AppFinanceBudgetsBudgetIdRoute: AppFinanceBudgetsBudgetIdRoute,
  AppFinanceBudgetsAdjustmentsRoute: AppFinanceBudgetsAdjustmentsRoute,
  AppFinanceBudgetsAllocationRoute: AppFinanceBudgetsAllocationRoute,
  AppFinanceBudgetsAnalyticsRoute: AppFinanceBudgetsAnalyticsRoute,
  AppFinanceBudgetsApprovalRoute: AppFinanceBudgetsApprovalRoute,
  AppFinanceBudgetsComparisonRoute: AppFinanceBudgetsComparisonRoute,
  AppFinanceBudgetsHistoryRoute: AppFinanceBudgetsHistoryRoute,
}

const AppFinanceBudgetsRouteWithChildren =
  AppFinanceBudgetsRoute._addFileChildren(AppFinanceBudgetsRouteChildren)

interface AppFinanceRouteChildren {
  AppFinanceAiRoute: typeof AppFinanceAiRoute
  AppFinanceApprovalsRoute: typeof AppFinanceApprovalsRoute
  AppFinanceBudgetsRoute: typeof AppFinanceBudgetsRouteWithChildren
  AppFinanceExpensesRoute: typeof AppFinanceExpensesRoute
  AppFinancePayrollReviewRoute: typeof AppFinancePayrollReviewRoute
  AppFinanceReportsRoute: typeof AppFinanceReportsRoute
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
}

const AppFinanceRouteChildren: AppFinanceRouteChildren = {
  AppFinanceAiRoute: AppFinanceAiRoute,
  AppFinanceApprovalsRoute: AppFinanceApprovalsRoute,
  AppFinanceBudgetsRoute: AppFinanceBudgetsRouteWithChildren,
  AppFinanceExpensesRoute: AppFinanceExpensesRoute,
  AppFinancePayrollReviewRoute: AppFinancePayrollReviewRoute,
  AppFinanceReportsRoute: AppFinanceReportsRoute,
  AppFinanceIndexRoute: AppFinanceIndexRoute,
}

const AppFinanceRouteWithChildren = AppFinanceRoute._addFileChildren(
  AppFinanceRouteChildren,
)

interface AppHrAttendanceRouteChildren {
  AppHrAttendanceGeofenceRoute: typeof AppHrAttendanceGeofenceRoute
  AppHrAttendanceIssuesRoute: typeof AppHrAttendanceIssuesRoute
  AppHrAttendanceVerificationRoute: typeof AppHrAttendanceVerificationRoute
}

const AppHrAttendanceRouteChildren: AppHrAttendanceRouteChildren = {
  AppHrAttendanceGeofenceRoute: AppHrAttendanceGeofenceRoute,
  AppHrAttendanceIssuesRoute: AppHrAttendanceIssuesRoute,
  AppHrAttendanceVerificationRoute: AppHrAttendanceVerificationRoute,
}

const AppHrAttendanceRouteWithChildren = AppHrAttendanceRoute._addFileChildren(
  AppHrAttendanceRouteChildren,
)

interface AppHrPayrollRouteChildren {
  AppHrPayrollApprovalsRoute: typeof AppHrPayrollApprovalsRoute
  AppHrPayrollHistoryRoute: typeof AppHrPayrollHistoryRoute
}

const AppHrPayrollRouteChildren: AppHrPayrollRouteChildren = {
  AppHrPayrollApprovalsRoute: AppHrPayrollApprovalsRoute,
  AppHrPayrollHistoryRoute: AppHrPayrollHistoryRoute,
}

const AppHrPayrollRouteWithChildren = AppHrPayrollRoute._addFileChildren(
  AppHrPayrollRouteChildren,
)

interface AppHrRecruitmentRouteChildren {
  AppHrRecruitmentInterviewsRoute: typeof AppHrRecruitmentInterviewsRoute
}

const AppHrRecruitmentRouteChildren: AppHrRecruitmentRouteChildren = {
  AppHrRecruitmentInterviewsRoute: AppHrRecruitmentInterviewsRoute,
}

const AppHrRecruitmentRouteWithChildren =
  AppHrRecruitmentRoute._addFileChildren(AppHrRecruitmentRouteChildren)

interface AppHrRouteChildren {
  AppHrAiRoute: typeof AppHrAiRoute
  AppHrAttendanceRoute: typeof AppHrAttendanceRouteWithChildren
  AppHrBenefitsRoute: typeof AppHrBenefitsRoute
  AppHrDeductionsRoute: typeof AppHrDeductionsRoute
  AppHrDocumentsRoute: typeof AppHrDocumentsRoute
  AppHrEmployeesRoute: typeof AppHrEmployeesRoute
  AppHrLeaveRoute: typeof AppHrLeaveRoute
  AppHrNotificationsRoute: typeof AppHrNotificationsRoute
  AppHrPayrollRoute: typeof AppHrPayrollRouteWithChildren
  AppHrPerformanceRoute: typeof AppHrPerformanceRoute
  AppHrRecruitmentRoute: typeof AppHrRecruitmentRouteWithChildren
  AppHrReportsRoute: typeof AppHrReportsRoute
  AppHrScheduleRoute: typeof AppHrScheduleRoute
  AppHrSettingsRoute: typeof AppHrSettingsRoute
  AppHrTrainingRoute: typeof AppHrTrainingRoute
  AppHrWorkforceRoute: typeof AppHrWorkforceRoute
}

const AppHrRouteChildren: AppHrRouteChildren = {
  AppHrAiRoute: AppHrAiRoute,
  AppHrAttendanceRoute: AppHrAttendanceRouteWithChildren,
  AppHrBenefitsRoute: AppHrBenefitsRoute,
  AppHrDeductionsRoute: AppHrDeductionsRoute,
  AppHrDocumentsRoute: AppHrDocumentsRoute,
  AppHrEmployeesRoute: AppHrEmployeesRoute,
  AppHrLeaveRoute: AppHrLeaveRoute,
  AppHrNotificationsRoute: AppHrNotificationsRoute,
  AppHrPayrollRoute: AppHrPayrollRouteWithChildren,
  AppHrPerformanceRoute: AppHrPerformanceRoute,
  AppHrRecruitmentRoute: AppHrRecruitmentRouteWithChildren,
  AppHrReportsRoute: AppHrReportsRoute,
  AppHrScheduleRoute: AppHrScheduleRoute,
  AppHrSettingsRoute: AppHrSettingsRoute,
  AppHrTrainingRoute: AppHrTrainingRoute,
  AppHrWorkforceRoute: AppHrWorkforceRoute,
}

const AppHrRouteWithChildren = AppHrRoute._addFileChildren(AppHrRouteChildren)

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdAnalyticsRoute: typeof AppProjectsProjectIdAnalyticsRoute
  AppProjectsProjectIdDailyLogsRoute: typeof AppProjectsProjectIdDailyLogsRoute
  AppProjectsProjectIdDocumentsRoute: typeof AppProjectsProjectIdDocumentsRoute
  AppProjectsProjectIdEquipmentRoute: typeof AppProjectsProjectIdEquipmentRoute
  AppProjectsProjectIdIssuesRoute: typeof AppProjectsProjectIdIssuesRoute
  AppProjectsProjectIdMilestonesRoute: typeof AppProjectsProjectIdMilestonesRoute
  AppProjectsProjectIdQualityRoute: typeof AppProjectsProjectIdQualityRoute
  AppProjectsProjectIdRisksRoute: typeof AppProjectsProjectIdRisksRoute
  AppProjectsProjectIdTasksRoute: typeof AppProjectsProjectIdTasksRoute
  AppProjectsProjectIdTimelineRoute: typeof AppProjectsProjectIdTimelineRoute
  AppProjectsProjectIdWorkforceRoute: typeof AppProjectsProjectIdWorkforceRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdAnalyticsRoute: AppProjectsProjectIdAnalyticsRoute,
  AppProjectsProjectIdDailyLogsRoute: AppProjectsProjectIdDailyLogsRoute,
  AppProjectsProjectIdDocumentsRoute: AppProjectsProjectIdDocumentsRoute,
  AppProjectsProjectIdEquipmentRoute: AppProjectsProjectIdEquipmentRoute,
  AppProjectsProjectIdIssuesRoute: AppProjectsProjectIdIssuesRoute,
  AppProjectsProjectIdMilestonesRoute: AppProjectsProjectIdMilestonesRoute,
  AppProjectsProjectIdQualityRoute: AppProjectsProjectIdQualityRoute,
  AppProjectsProjectIdRisksRoute: AppProjectsProjectIdRisksRoute,
  AppProjectsProjectIdTasksRoute: AppProjectsProjectIdTasksRoute,
  AppProjectsProjectIdTimelineRoute: AppProjectsProjectIdTimelineRoute,
  AppProjectsProjectIdWorkforceRoute: AppProjectsProjectIdWorkforceRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppArchitectRoute: typeof AppArchitectRouteWithChildren
  AppAuditRoute: typeof AppAuditRoute
  AppConsultantRoute: typeof AppConsultantRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEngineerRoute: typeof AppEngineerRoute
  AppFinanceRoute: typeof AppFinanceRouteWithChildren
  AppHrRoute: typeof AppHrRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSiteRoute: typeof AppSiteRoute
  AppSupportRoute: typeof AppSupportRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppArchitectRoute: AppArchitectRouteWithChildren,
  AppAuditRoute: AppAuditRoute,
  AppConsultantRoute: AppConsultantRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEngineerRoute: AppEngineerRoute,
  AppFinanceRoute: AppFinanceRouteWithChildren,
  AppHrRoute: AppHrRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSiteRoute: AppSiteRoute,
  AppSupportRoute: AppSupportRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
