/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkflowsRouteImport } from './routes/_app.workflows'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppSiteRouteImport } from './routes/_app.site'
import { Route as AppResourcesRouteImport } from './routes/_app.resources'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppEngineerRouteImport } from './routes/_app.engineer'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConsultantRouteImport } from './routes/_app.consultant'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppArchitectRouteImport } from './routes/_app.architect'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppAiInsightsRouteImport } from './routes/_app.ai-insights'
import { Route as AppFinanceIndexRouteImport } from './routes/_app.finance.index'
import { Route as AppProjectsNewRouteImport } from './routes/_app.projects.new'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppFinanceReportsRouteImport } from './routes/_app.finance.reports'
import { Route as AppFinancePayrollReviewRouteImport } from './routes/_app.finance.payroll-review'
import { Route as AppFinanceExpensesRouteImport } from './routes/_app.finance.expenses'
import { Route as AppFinanceBudgetsRouteImport } from './routes/_app.finance.budgets'
import { Route as AppFinanceApprovalsRouteImport } from './routes/_app.finance.approvals'
import { Route as AppFinanceAiRouteImport } from './routes/_app.finance.ai'
import { Route as AppProjectsProjectIdWorkforceRouteImport } from './routes/_app.projects.$projectId.workforce'
import { Route as AppProjectsProjectIdTimelineRouteImport } from './routes/_app.projects.$projectId.timeline'
import { Route as AppProjectsProjectIdTasksRouteImport } from './routes/_app.projects.$projectId.tasks'
import { Route as AppProjectsProjectIdRisksRouteImport } from './routes/_app.projects.$projectId.risks'
import { Route as AppProjectsProjectIdQualityRouteImport } from './routes/_app.projects.$projectId.quality'
import { Route as AppProjectsProjectIdMilestonesRouteImport } from './routes/_app.projects.$projectId.milestones'
import { Route as AppProjectsProjectIdIssuesRouteImport } from './routes/_app.projects.$projectId.issues'
import { Route as AppProjectsProjectIdEquipmentRouteImport } from './routes/_app.projects.$projectId.equipment'
import { Route as AppProjectsProjectIdDocumentsRouteImport } from './routes/_app.projects.$projectId.documents'
import { Route as AppProjectsProjectIdDailyLogsRouteImport } from './routes/_app.projects.$projectId.daily-logs'
import { Route as AppProjectsProjectIdAnalyticsRouteImport } from './routes/_app.projects.$projectId.analytics'
import { Route as AppFinanceBudgetsHistoryRouteImport } from './routes/_app.finance.budgets.history'
import { Route as AppFinanceBudgetsComparisonRouteImport } from './routes/_app.finance.budgets.comparison'
import { Route as AppFinanceBudgetsApprovalRouteImport } from './routes/_app.finance.budgets.approval'
import { Route as AppFinanceBudgetsAnalyticsRouteImport } from './routes/_app.finance.budgets.analytics'
import { Route as AppFinanceBudgetsAllocationRouteImport } from './routes/_app.finance.budgets.allocation'
import { Route as AppFinanceBudgetsAdjustmentsRouteImport } from './routes/_app.finance.budgets.adjustments'
import { Route as AppFinanceBudgetsBudgetIdRouteImport } from './routes/_app.finance.budgets.$budgetId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteRoute = AppSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppEngineerRoute = AppEngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultantRoute = AppConsultantRouteImport.update({
  id: '/consultant',
  path: '/consultant',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppArchitectRoute = AppArchitectRouteImport.update({
  id: '/architect',
  path: '/architect',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppFinanceReportsRoute = AppFinanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinancePayrollReviewRoute = AppFinancePayrollReviewRouteImport.update({
  id: '/payroll-review',
  path: '/payroll-review',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceExpensesRoute = AppFinanceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceBudgetsRoute = AppFinanceBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceApprovalsRoute = AppFinanceApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceAiRoute = AppFinanceAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppProjectsProjectIdWorkforceRoute =
  AppProjectsProjectIdWorkforceRouteImport.update({
    id: '/workforce',
    path: '/workforce',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdTimelineRoute =
  AppProjectsProjectIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdTasksRoute =
  AppProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdRisksRoute =
  AppProjectsProjectIdRisksRouteImport.update({
    id: '/risks',
    path: '/risks',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdQualityRoute =
  AppProjectsProjectIdQualityRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdMilestonesRoute =
  AppProjectsProjectIdMilestonesRouteImport.update({
    id: '/milestones',
    path: '/milestones',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdIssuesRoute =
  AppProjectsProjectIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdEquipmentRoute =
  AppProjectsProjectIdEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDocumentsRoute =
  AppProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDailyLogsRoute =
  AppProjectsProjectIdDailyLogsRouteImport.update({
    id: '/daily-logs',
    path: '/daily-logs',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdAnalyticsRoute =
  AppProjectsProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppFinanceBudgetsHistoryRoute =
  AppFinanceBudgetsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppFinanceBudgetsComparisonRoute =
  AppFinanceBudgetsComparisonRouteImport.update({
    id: '/comparison',
    path: '/comparison',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppFinanceBudgetsApprovalRoute =
  AppFinanceBudgetsApprovalRouteImport.update({
    id: '/approval',
    path: '/approval',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppFinanceBudgetsAnalyticsRoute =
  AppFinanceBudgetsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppFinanceBudgetsAllocationRoute =
  AppFinanceBudgetsAllocationRouteImport.update({
    id: '/allocation',
    path: '/allocation',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppFinanceBudgetsAdjustmentsRoute =
  AppFinanceBudgetsAdjustmentsRouteImport.update({
    id: '/adjustments',
    path: '/adjustments',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)
const AppFinanceBudgetsBudgetIdRoute =
  AppFinanceBudgetsBudgetIdRouteImport.update({
    id: '/$budgetId',
    path: '/$budgetId',
    getParentRoute: () => AppFinanceBudgetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/approvals': typeof AppApprovalsRoute
  '/architect': typeof AppArchitectRoute
  '/audit': typeof AppAuditRoute
  '/consultant': typeof AppConsultantRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/engineer': typeof AppEngineerRoute
  '/finance': typeof AppFinanceRouteWithChildren
  '/hr': typeof AppHrRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/resources': typeof AppResourcesRoute
  '/site': typeof AppSiteRoute
  '/support': typeof AppSupportRoute
  '/workflows': typeof AppWorkflowsRoute
  '/finance/ai': typeof AppFinanceAiRoute
  '/finance/approvals': typeof AppFinanceApprovalsRoute
  '/finance/budgets': typeof AppFinanceBudgetsRouteWithChildren
  '/finance/expenses': typeof AppFinanceExpensesRoute
  '/finance/payroll-review': typeof AppFinancePayrollReviewRoute
  '/finance/reports': typeof AppFinanceReportsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/finance/': typeof AppFinanceIndexRoute
  '/finance/budgets/$budgetId': typeof AppFinanceBudgetsBudgetIdRoute
  '/finance/budgets/adjustments': typeof AppFinanceBudgetsAdjustmentsRoute
  '/finance/budgets/allocation': typeof AppFinanceBudgetsAllocationRoute
  '/finance/budgets/analytics': typeof AppFinanceBudgetsAnalyticsRoute
  '/finance/budgets/approval': typeof AppFinanceBudgetsApprovalRoute
  '/finance/budgets/comparison': typeof AppFinanceBudgetsComparisonRoute
  '/finance/budgets/history': typeof AppFinanceBudgetsHistoryRoute
  '/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/daily-logs': typeof AppProjectsProjectIdDailyLogsRoute
  '/projects/$projectId/documents': typeof AppProjectsProjectIdDocumentsRoute
  '/projects/$projectId/equipment': typeof AppProjectsProjectIdEquipmentRoute
  '/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRoute
  '/projects/$projectId/milestones': typeof AppProjectsProjectIdMilestonesRoute
  '/projects/$projectId/quality': typeof AppProjectsProjectIdQualityRoute
  '/projects/$projectId/risks': typeof AppProjectsProjectIdRisksRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/projects/$projectId/timeline': typeof AppProjectsProjectIdTimelineRoute
  '/projects/$projectId/workforce': typeof AppProjectsProjectIdWorkforceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/approvals': typeof AppApprovalsRoute
  '/architect': typeof AppArchitectRoute
  '/audit': typeof AppAuditRoute
  '/consultant': typeof AppConsultantRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/engineer': typeof AppEngineerRoute
  '/hr': typeof AppHrRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/resources': typeof AppResourcesRoute
  '/site': typeof AppSiteRoute
  '/support': typeof AppSupportRoute
  '/workflows': typeof AppWorkflowsRoute
  '/finance/ai': typeof AppFinanceAiRoute
  '/finance/approvals': typeof AppFinanceApprovalsRoute
  '/finance/budgets': typeof AppFinanceBudgetsRouteWithChildren
  '/finance/expenses': typeof AppFinanceExpensesRoute
  '/finance/payroll-review': typeof AppFinancePayrollReviewRoute
  '/finance/reports': typeof AppFinanceReportsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/finance': typeof AppFinanceIndexRoute
  '/finance/budgets/$budgetId': typeof AppFinanceBudgetsBudgetIdRoute
  '/finance/budgets/adjustments': typeof AppFinanceBudgetsAdjustmentsRoute
  '/finance/budgets/allocation': typeof AppFinanceBudgetsAllocationRoute
  '/finance/budgets/analytics': typeof AppFinanceBudgetsAnalyticsRoute
  '/finance/budgets/approval': typeof AppFinanceBudgetsApprovalRoute
  '/finance/budgets/comparison': typeof AppFinanceBudgetsComparisonRoute
  '/finance/budgets/history': typeof AppFinanceBudgetsHistoryRoute
  '/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/daily-logs': typeof AppProjectsProjectIdDailyLogsRoute
  '/projects/$projectId/documents': typeof AppProjectsProjectIdDocumentsRoute
  '/projects/$projectId/equipment': typeof AppProjectsProjectIdEquipmentRoute
  '/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRoute
  '/projects/$projectId/milestones': typeof AppProjectsProjectIdMilestonesRoute
  '/projects/$projectId/quality': typeof AppProjectsProjectIdQualityRoute
  '/projects/$projectId/risks': typeof AppProjectsProjectIdRisksRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/projects/$projectId/timeline': typeof AppProjectsProjectIdTimelineRoute
  '/projects/$projectId/workforce': typeof AppProjectsProjectIdWorkforceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-insights': typeof AppAiInsightsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/architect': typeof AppArchitectRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/consultant': typeof AppConsultantRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/engineer': typeof AppEngineerRoute
  '/_app/finance': typeof AppFinanceRouteWithChildren
  '/_app/hr': typeof AppHrRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/site': typeof AppSiteRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/workflows': typeof AppWorkflowsRoute
  '/_app/finance/ai': typeof AppFinanceAiRoute
  '/_app/finance/approvals': typeof AppFinanceApprovalsRoute
  '/_app/finance/budgets': typeof AppFinanceBudgetsRouteWithChildren
  '/_app/finance/expenses': typeof AppFinanceExpensesRoute
  '/_app/finance/payroll-review': typeof AppFinancePayrollReviewRoute
  '/_app/finance/reports': typeof AppFinanceReportsRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/finance/': typeof AppFinanceIndexRoute
  '/_app/finance/budgets/$budgetId': typeof AppFinanceBudgetsBudgetIdRoute
  '/_app/finance/budgets/adjustments': typeof AppFinanceBudgetsAdjustmentsRoute
  '/_app/finance/budgets/allocation': typeof AppFinanceBudgetsAllocationRoute
  '/_app/finance/budgets/analytics': typeof AppFinanceBudgetsAnalyticsRoute
  '/_app/finance/budgets/approval': typeof AppFinanceBudgetsApprovalRoute
  '/_app/finance/budgets/comparison': typeof AppFinanceBudgetsComparisonRoute
  '/_app/finance/budgets/history': typeof AppFinanceBudgetsHistoryRoute
  '/_app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/_app/projects/$projectId/daily-logs': typeof AppProjectsProjectIdDailyLogsRoute
  '/_app/projects/$projectId/documents': typeof AppProjectsProjectIdDocumentsRoute
  '/_app/projects/$projectId/equipment': typeof AppProjectsProjectIdEquipmentRoute
  '/_app/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRoute
  '/_app/projects/$projectId/milestones': typeof AppProjectsProjectIdMilestonesRoute
  '/_app/projects/$projectId/quality': typeof AppProjectsProjectIdQualityRoute
  '/_app/projects/$projectId/risks': typeof AppProjectsProjectIdRisksRoute
  '/_app/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/_app/projects/$projectId/timeline': typeof AppProjectsProjectIdTimelineRoute
  '/_app/projects/$projectId/workforce': typeof AppProjectsProjectIdWorkforceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/approvals'
    | '/architect'
    | '/audit'
    | '/consultant'
    | '/dashboard'
    | '/documents'
    | '/engineer'
    | '/finance'
    | '/hr'
    | '/projects'
    | '/reports'
    | '/resources'
    | '/site'
    | '/support'
    | '/workflows'
    | '/finance/ai'
    | '/finance/approvals'
    | '/finance/budgets'
    | '/finance/expenses'
    | '/finance/payroll-review'
    | '/finance/reports'
    | '/projects/$projectId'
    | '/projects/new'
    | '/finance/'
    | '/finance/budgets/$budgetId'
    | '/finance/budgets/adjustments'
    | '/finance/budgets/allocation'
    | '/finance/budgets/analytics'
    | '/finance/budgets/approval'
    | '/finance/budgets/comparison'
    | '/finance/budgets/history'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/daily-logs'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/equipment'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/milestones'
    | '/projects/$projectId/quality'
    | '/projects/$projectId/risks'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId/workforce'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/approvals'
    | '/architect'
    | '/audit'
    | '/consultant'
    | '/dashboard'
    | '/documents'
    | '/engineer'
    | '/hr'
    | '/projects'
    | '/reports'
    | '/resources'
    | '/site'
    | '/support'
    | '/workflows'
    | '/finance/ai'
    | '/finance/approvals'
    | '/finance/budgets'
    | '/finance/expenses'
    | '/finance/payroll-review'
    | '/finance/reports'
    | '/projects/$projectId'
    | '/projects/new'
    | '/finance'
    | '/finance/budgets/$budgetId'
    | '/finance/budgets/adjustments'
    | '/finance/budgets/allocation'
    | '/finance/budgets/analytics'
    | '/finance/budgets/approval'
    | '/finance/budgets/comparison'
    | '/finance/budgets/history'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/daily-logs'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/equipment'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/milestones'
    | '/projects/$projectId/quality'
    | '/projects/$projectId/risks'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId/workforce'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/ai-insights'
    | '/_app/approvals'
    | '/_app/architect'
    | '/_app/audit'
    | '/_app/consultant'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/engineer'
    | '/_app/finance'
    | '/_app/hr'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/resources'
    | '/_app/site'
    | '/_app/support'
    | '/_app/workflows'
    | '/_app/finance/ai'
    | '/_app/finance/approvals'
    | '/_app/finance/budgets'
    | '/_app/finance/expenses'
    | '/_app/finance/payroll-review'
    | '/_app/finance/reports'
    | '/_app/projects/$projectId'
    | '/_app/projects/new'
    | '/_app/finance/'
    | '/_app/finance/budgets/$budgetId'
    | '/_app/finance/budgets/adjustments'
    | '/_app/finance/budgets/allocation'
    | '/_app/finance/budgets/analytics'
    | '/_app/finance/budgets/approval'
    | '/_app/finance/budgets/comparison'
    | '/_app/finance/budgets/history'
    | '/_app/projects/$projectId/analytics'
    | '/_app/projects/$projectId/daily-logs'
    | '/_app/projects/$projectId/documents'
    | '/_app/projects/$projectId/equipment'
    | '/_app/projects/$projectId/issues'
    | '/_app/projects/$projectId/milestones'
    | '/_app/projects/$projectId/quality'
    | '/_app/projects/$projectId/risks'
    | '/_app/projects/$projectId/tasks'
    | '/_app/projects/$projectId/timeline'
    | '/_app/projects/$projectId/workforce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/site': {
      id: '/_app/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof AppSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/engineer': {
      id: '/_app/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof AppEngineerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultant': {
      id: '/_app/consultant'
      path: '/consultant'
      fullPath: '/consultant'
      preLoaderRoute: typeof AppConsultantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/architect': {
      id: '/_app/architect'
      path: '/architect'
      fullPath: '/architect'
      preLoaderRoute: typeof AppArchitectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-insights': {
      id: '/_app/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/': {
      id: '/_app/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/finance/reports': {
      id: '/_app/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof AppFinanceReportsRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/finance/payroll-review': {
      id: '/_app/finance/payroll-review'
      path: '/payroll-review'
      fullPath: '/finance/payroll-review'
      preLoaderRoute: typeof AppFinancePayrollReviewRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/finance/expenses': {
      id: '/_app/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof AppFinanceExpensesRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/finance/budgets': {
      id: '/_app/finance/budgets'
      path: '/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof AppFinanceBudgetsRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/finance/approvals': {
      id: '/_app/finance/approvals'
      path: '/approvals'
      fullPath: '/finance/approvals'
      preLoaderRoute: typeof AppFinanceApprovalsRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/finance/ai': {
      id: '/_app/finance/ai'
      path: '/ai'
      fullPath: '/finance/ai'
      preLoaderRoute: typeof AppFinanceAiRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/_app/projects/$projectId/workforce': {
      id: '/_app/projects/$projectId/workforce'
      path: '/workforce'
      fullPath: '/projects/$projectId/workforce'
      preLoaderRoute: typeof AppProjectsProjectIdWorkforceRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/timeline': {
      id: '/_app/projects/$projectId/timeline'
      path: '/timeline'
      fullPath: '/projects/$projectId/timeline'
      preLoaderRoute: typeof AppProjectsProjectIdTimelineRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/tasks': {
      id: '/_app/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof AppProjectsProjectIdTasksRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/risks': {
      id: '/_app/projects/$projectId/risks'
      path: '/risks'
      fullPath: '/projects/$projectId/risks'
      preLoaderRoute: typeof AppProjectsProjectIdRisksRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/quality': {
      id: '/_app/projects/$projectId/quality'
      path: '/quality'
      fullPath: '/projects/$projectId/quality'
      preLoaderRoute: typeof AppProjectsProjectIdQualityRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/milestones': {
      id: '/_app/projects/$projectId/milestones'
      path: '/milestones'
      fullPath: '/projects/$projectId/milestones'
      preLoaderRoute: typeof AppProjectsProjectIdMilestonesRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/issues': {
      id: '/_app/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/equipment': {
      id: '/_app/projects/$projectId/equipment'
      path: '/equipment'
      fullPath: '/projects/$projectId/equipment'
      preLoaderRoute: typeof AppProjectsProjectIdEquipmentRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/documents': {
      id: '/_app/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof AppProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/daily-logs': {
      id: '/_app/projects/$projectId/daily-logs'
      path: '/daily-logs'
      fullPath: '/projects/$projectId/daily-logs'
      preLoaderRoute: typeof AppProjectsProjectIdDailyLogsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/analytics': {
      id: '/_app/projects/$projectId/analytics'
      path: '/analytics'
      fullPath: '/projects/$projectId/analytics'
      preLoaderRoute: typeof AppProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/finance/budgets/history': {
      id: '/_app/finance/budgets/history'
      path: '/history'
      fullPath: '/finance/budgets/history'
      preLoaderRoute: typeof AppFinanceBudgetsHistoryRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/finance/budgets/comparison': {
      id: '/_app/finance/budgets/comparison'
      path: '/comparison'
      fullPath: '/finance/budgets/comparison'
      preLoaderRoute: typeof AppFinanceBudgetsComparisonRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/finance/budgets/approval': {
      id: '/_app/finance/budgets/approval'
      path: '/approval'
      fullPath: '/finance/budgets/approval'
      preLoaderRoute: typeof AppFinanceBudgetsApprovalRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/finance/budgets/analytics': {
      id: '/_app/finance/budgets/analytics'
      path: '/analytics'
      fullPath: '/finance/budgets/analytics'
      preLoaderRoute: typeof AppFinanceBudgetsAnalyticsRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/finance/budgets/allocation': {
      id: '/_app/finance/budgets/allocation'
      path: '/allocation'
      fullPath: '/finance/budgets/allocation'
      preLoaderRoute: typeof AppFinanceBudgetsAllocationRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/finance/budgets/adjustments': {
      id: '/_app/finance/budgets/adjustments'
      path: '/adjustments'
      fullPath: '/finance/budgets/adjustments'
      preLoaderRoute: typeof AppFinanceBudgetsAdjustmentsRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
    '/_app/finance/budgets/$budgetId': {
      id: '/_app/finance/budgets/$budgetId'
      path: '/$budgetId'
      fullPath: '/finance/budgets/$budgetId'
      preLoaderRoute: typeof AppFinanceBudgetsBudgetIdRouteImport
      parentRoute: typeof AppFinanceBudgetsRoute
    }
  }
}

interface AppFinanceBudgetsRouteChildren {
  AppFinanceBudgetsBudgetIdRoute: typeof AppFinanceBudgetsBudgetIdRoute
  AppFinanceBudgetsAdjustmentsRoute: typeof AppFinanceBudgetsAdjustmentsRoute
  AppFinanceBudgetsAllocationRoute: typeof AppFinanceBudgetsAllocationRoute
  AppFinanceBudgetsAnalyticsRoute: typeof AppFinanceBudgetsAnalyticsRoute
  AppFinanceBudgetsApprovalRoute: typeof AppFinanceBudgetsApprovalRoute
  AppFinanceBudgetsComparisonRoute: typeof AppFinanceBudgetsComparisonRoute
  AppFinanceBudgetsHistoryRoute: typeof AppFinanceBudgetsHistoryRoute
}

const AppFinanceBudgetsRouteChildren: AppFinanceBudgetsRouteChildren = {
  AppFinanceBudgetsBudgetIdRoute: AppFinanceBudgetsBudgetIdRoute,
  AppFinanceBudgetsAdjustmentsRoute: AppFinanceBudgetsAdjustmentsRoute,
  AppFinanceBudgetsAllocationRoute: AppFinanceBudgetsAllocationRoute,
  AppFinanceBudgetsAnalyticsRoute: AppFinanceBudgetsAnalyticsRoute,
  AppFinanceBudgetsApprovalRoute: AppFinanceBudgetsApprovalRoute,
  AppFinanceBudgetsComparisonRoute: AppFinanceBudgetsComparisonRoute,
  AppFinanceBudgetsHistoryRoute: AppFinanceBudgetsHistoryRoute,
}

const AppFinanceBudgetsRouteWithChildren =
  AppFinanceBudgetsRoute._addFileChildren(AppFinanceBudgetsRouteChildren)

interface AppFinanceRouteChildren {
  AppFinanceAiRoute: typeof AppFinanceAiRoute
  AppFinanceApprovalsRoute: typeof AppFinanceApprovalsRoute
  AppFinanceBudgetsRoute: typeof AppFinanceBudgetsRouteWithChildren
  AppFinanceExpensesRoute: typeof AppFinanceExpensesRoute
  AppFinancePayrollReviewRoute: typeof AppFinancePayrollReviewRoute
  AppFinanceReportsRoute: typeof AppFinanceReportsRoute
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
}

const AppFinanceRouteChildren: AppFinanceRouteChildren = {
  AppFinanceAiRoute: AppFinanceAiRoute,
  AppFinanceApprovalsRoute: AppFinanceApprovalsRoute,
  AppFinanceBudgetsRoute: AppFinanceBudgetsRouteWithChildren,
  AppFinanceExpensesRoute: AppFinanceExpensesRoute,
  AppFinancePayrollReviewRoute: AppFinancePayrollReviewRoute,
  AppFinanceReportsRoute: AppFinanceReportsRoute,
  AppFinanceIndexRoute: AppFinanceIndexRoute,
}

const AppFinanceRouteWithChildren = AppFinanceRoute._addFileChildren(
  AppFinanceRouteChildren,
)

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdAnalyticsRoute: typeof AppProjectsProjectIdAnalyticsRoute
  AppProjectsProjectIdDailyLogsRoute: typeof AppProjectsProjectIdDailyLogsRoute
  AppProjectsProjectIdDocumentsRoute: typeof AppProjectsProjectIdDocumentsRoute
  AppProjectsProjectIdEquipmentRoute: typeof AppProjectsProjectIdEquipmentRoute
  AppProjectsProjectIdIssuesRoute: typeof AppProjectsProjectIdIssuesRoute
  AppProjectsProjectIdMilestonesRoute: typeof AppProjectsProjectIdMilestonesRoute
  AppProjectsProjectIdQualityRoute: typeof AppProjectsProjectIdQualityRoute
  AppProjectsProjectIdRisksRoute: typeof AppProjectsProjectIdRisksRoute
  AppProjectsProjectIdTasksRoute: typeof AppProjectsProjectIdTasksRoute
  AppProjectsProjectIdTimelineRoute: typeof AppProjectsProjectIdTimelineRoute
  AppProjectsProjectIdWorkforceRoute: typeof AppProjectsProjectIdWorkforceRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdAnalyticsRoute: AppProjectsProjectIdAnalyticsRoute,
  AppProjectsProjectIdDailyLogsRoute: AppProjectsProjectIdDailyLogsRoute,
  AppProjectsProjectIdDocumentsRoute: AppProjectsProjectIdDocumentsRoute,
  AppProjectsProjectIdEquipmentRoute: AppProjectsProjectIdEquipmentRoute,
  AppProjectsProjectIdIssuesRoute: AppProjectsProjectIdIssuesRoute,
  AppProjectsProjectIdMilestonesRoute: AppProjectsProjectIdMilestonesRoute,
  AppProjectsProjectIdQualityRoute: AppProjectsProjectIdQualityRoute,
  AppProjectsProjectIdRisksRoute: AppProjectsProjectIdRisksRoute,
  AppProjectsProjectIdTasksRoute: AppProjectsProjectIdTasksRoute,
  AppProjectsProjectIdTimelineRoute: AppProjectsProjectIdTimelineRoute,
  AppProjectsProjectIdWorkforceRoute: AppProjectsProjectIdWorkforceRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppArchitectRoute: typeof AppArchitectRoute
  AppAuditRoute: typeof AppAuditRoute
  AppConsultantRoute: typeof AppConsultantRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEngineerRoute: typeof AppEngineerRoute
  AppFinanceRoute: typeof AppFinanceRouteWithChildren
  AppHrRoute: typeof AppHrRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSiteRoute: typeof AppSiteRoute
  AppSupportRoute: typeof AppSupportRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppArchitectRoute: AppArchitectRoute,
  AppAuditRoute: AppAuditRoute,
  AppConsultantRoute: AppConsultantRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEngineerRoute: AppEngineerRoute,
  AppFinanceRoute: AppFinanceRouteWithChildren,
  AppHrRoute: AppHrRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSiteRoute: AppSiteRoute,
  AppSupportRoute: AppSupportRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
